---
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '00 3 * * *'

name: CI

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: nightly
          components: clippy, rustfmt

      - name: Build
        run: cargo build

      - name: Style
        run: |
          cargo fmt --check
          cargo clippy -- -D clippy::all
